src/index.js

In the generated CSS the SVG data urls are not quoted inside `url()` this leads to them not actually showing up (in Chrome at least). This is no problem on the demo site since `clean-css` fixes the urls and adds quotes.
Also W3 [recommends](https://drafts.csswg.org/css-values-3/#urls) using quotes in urls.

Add quotes in background-image urls

---

package.json

Internally we are using tailwindcss/plugin, but we don't mark it as a
peerDependency or a normal dependency in our package.json. This means
that this plugin will fail in a monorepo environment when dependnecies
get hoisted. This is because now there is no link to tailwind itself.
Marking it as a peerDependency should fix this, because now there is a
link. People that already have tailwind installed are good to go. People
that use monorepo's should benefit from this additional information.
Side note: NPM 7 starts installing peerDependencies for us https://github.com/npm/rfcs/blob/latest/implemented/0025-install-peer-deps.md
which is nice, because if we added an `explicit` dependency to Tailwind,
then we would always reference our dependency and not the user's
dependency.
Closes: #31

mark tailwindcss as a peerDependency

---

README.md
src/index.js

Addresses #11 , #20 , #22
This intentionally keeps the code pretty dumb. Though, rather than using a ternary for every single selector, I opted to pass the selector string options to a simple function to determine whether to use `.form-` classes or not. This keeps it _somewhat_ cleaner.
If you'd like to do a simple test, paste in [the kitchen sink html code here](https://github.com/tailwindlabs/tailwindcss-forms/files/5895736/kitchen-sink.txt) and toggle the `useFormClasses` boolean option (and remove altogether).
```
plugins: [
require("@tailwindcss/forms")({
useFormClasses: false,
}),
],
```
The kitchen sink demo HTML is essentially duplicated. The first top set, being the original untouched kitchen sink, should work as intended without the option present, or set to `false`. (The bottom …

Adds selector ‘strategy’ plugin option

---

src/index.js

The default should be `base`,  not `class`.
Fixes #60.

Fix default strategy

---

src/index.js

Totally my fault on this one for the bad previous PR... Apologies.
Just in case anyone has reported this or similar:
This typo _really_ rears it's ugly head when using some postcss optimizations that combine style declarations (cssnano, perhaps?), thus breaking the background colors for checkboxes & radio buttons when using the `class` strategy.
Attempting to merge styles like this:
```
.form-checkbox:checked, .form-radio:checked {
border-color: transparent;
background-color: currentColor;
background-size: 100% 100%;
background-position: center;
background-repeat: no-repeat;
}
```
into others like so:
```
.form-checkbox:checked,.form-checkbox:checked:focus,.form-checkbox:checked:hover,.form-checkbox:indeterminate,.form-checkbox:indeterminate:focus,.form-checkbox:indeterminate:hover,.form-r …
```

Fix typo breaking background colors on checkboxes & radio buttons

---

src/index.js

This PR adds a reset for the shadow to each input element, this is necessary because we are trying to get rid of the universal selector. 
See: https://github.com/tailwindlabs/tailwindcss/pull/5517
Fixes: https://github.com/tailwindlabs/tailwindcss/issues/5042

Add default box shadow reset

---

package.json
src/index.js

The color palette is slightly different in the upcoming Tailwind CSS v3 release, and the format of the default config file has changed to define `colors` as a function. This means referencing `defaultTheme.colors` doesn't work the way it did in v2, so this PR updates the forms plugin to pull the default colors directly from `tailwindcss/colors` instead.

Pull colors from tailwindcss/colors, not defaultTheme

---

src/index.js

Currently we cannot use Tailwind's `base` layer because we are migrating our product from Bootstrap. Due to this problem I noticed that probably `.form-*` classes should not be in the `base` bucket but in the `component` instead when using `strategy: 'class'`.
With this change classes are added in `components` bucket.
PS: I was inspired by #66, but don't know why has been closed.
Closes: #64

Use `addComponents` for class strategy

---

CHANGELOG.md
src/index.js

On macOS Safari there is additional padding on some pseudo elements rendered inside of the input element's Shadow DOM. This removes that extra padding.
Fixes #95

Fix extra height on Safari date/time inputs

---

CHANGELOG.md
src/index.js

These are meant to be fallback styles — not overwritten declarations.
Fixes #112

Remove duplicate `outline` property

---

CHANGELOG.md
package.json
src/index.js

Until recently FF only supported the non-standard `color-adjust` property. Now that it supports `print-color-adjust` autoprefixer generates warnings when using the non-standard property.
Fixes https://github.com/tailwindlabs/tailwindcss/issues/8250
Fixes #114

Fix autoprefixer warning about `color-adjust`

---

package.json
src/index.d.ts

This PR is a continuation of #117 with a few changes. These changes include:
- Refactored to use a simple function instead. This way it doesn't rely on the `@types/tailwindcss` Definetely Typed repo which could cause issues when we release Tailwind CSS 3.1 with our own types.
- Use `export = plugin` instead of `export default plugin` so that it is compatible with `module.export` which is what most people use.
Closes: #117

Add type declaration

---

src/index.js

This PR provides a temporary solution by manually resolving the `<alpha-value>` from Tailwind CSS.
We are going to implement a proper fix (related issue: https://github.com/tailwindlabs/tailwindcss/issues/9143)
We will require a proper fix so that custom themes also work as expected.
But for now, this will make sure that the CSS is at least not invalid.
Fixes: #131

Fix incorrect `<alpha-value>`

---

README.md
src/index.js

Allow for `<input />` elements without the `type` attribute (eg. which defaults to a text input), which [may be required by certain codebases](https://github.com/tailwindlabs/tailwindcss-forms/issues/127#issuecomment-1634153557):
```html
<input /> 
```
Also removed the note from the readme, which isn't required anymore if my approach works
[Preview](https://tailwindcss-forms-git-fork-karlhorky-patch-1-tailwindlabs.vercel.app/) looks good - allows for overriding via A) utility classes and also B) `input` selector:

Allow for <input> without `type`

---

CHANGELOG.md
src/index.js

In the Windows theme "High Contrast White" our checked checkboxes weren't distinguishable from unchecked ones. This happens because colors are overridden by the browser / OS but  `url()` background images are still displayed — and our checkmark SVG background has `fill="white"`.
This resets the checkbox (and radio buttons) to `appearance: auto` such that the appearance is entirely controlled by the browser in forced colors mode.

Use normal `checkbox` and `radio` appearance in `forced-colors` mode

---

CHANGELOG.md
package.json

Now that we have support for it, we should make `npm install @tailwindcss/forms` not fail 🙂 
The change was tested by installing it via a tarball.

Update peer dependency version to include 4.0.0-alpha.20

---

.github/workflows/prepare-release.yml
.github/workflows/release-insiders.yml
.github/workflows/release.yml
CHANGELOG.md

This brings over the (slightly modernized) CI setup from https://github.com/tailwindlabs/tailwindcss-typography/ and other packages so that we can run a release from GitHub actions.

Add CI pipeline for releases and clean up the workflows

---

CHANGELOG.md
src/index.js

Right now if your `gray.500` color includes a CSS variable, the chevron on your select elements will disappear because URLs in `background-image` can't use CSS variables.
This PR just ensures that if there's a variable in your color, we fallback to the default `gray.500` so at least the chevron doesn't disappear.
Fixes #165.

Fallback to static chevron color if theme is using variables

---

index.html

`<select>` element should have a larger right-padding to accommodate the dropdown arrow.
However, the underline themed `<select>` had a `px-0.5` set, causing long text to show above the arrow.
- ![Underline](https://github.com/user-attachments/assets/58f1e6b3-7fb8-4b23-80d0-f55635b5b511)
- ![Unstyled](https://github.com/user-attachments/assets/f29979d7-ece9-4e58-b6b0-38d96b251182)
- ![Simple](https://github.com/user-attachments/assets/b6494a6c-cdfa-4495-ace3-4f857b4bee23)
- ![Solid](https://github.com/user-attachments/assets/68497aea-d5f1-4442-8280-69ec0fcb1099)

fix: underline select padding

---

.prettierrc
README.md
index.html
kitchen-sink.html
package-lock.json
package.json
src/index.d.ts

Sorted HTML classes using the official [prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss#readme) plugin.
A CLI command has been added to format all files.

chore: sort prettier classes with prettier

---

index.html

Sorry for the dual PR. Follow up for https://github.com/tailwindlabs/tailwindcss-forms/pull/168
I believe `pr-10` should be applied for consistency. [explanation](https://github.com/tailwindlabs/tailwindcss-forms/pull/168#issuecomment-2401144763)
Also, the updated `index.html` does not seems to be deployed to production.
https://tailwindcss-forms.vercel.app/

chore: update underline select padding

---

CHANGELOG.md
package.json

Same as https://github.com/tailwindlabs/tailwindcss-typography/pull/163 but for beta releases.

Update peer dependency version to include 4.0.0-beta.1
